GET http://localhost:3003/api/entry

###

POST http://localhost:3003/api/entry
Content-Type: application/json

{
    "title": "Enrollment",
    "importance": "2",
    "sched_time": 23,
    "description": "Need to enroll in CS130 and MGMT170",
    "date": "2/16/2024"
}

###
GET http://localhost:3003/api/entry/65cdb991df87633f898ecd82

###
PUT http://localhost:3003/api/entry/65cdb991df87633f898ecd82 HTTP/1.1
Content-Type: application/json

{
    "importance": 5
}